### PR TITLE
Merge all actions by channel

### PR DESCRIPTION
**Pull request by vinceyyy**

### CODE REVIEW

**Comment by silgal** [comment]
@vinceyyy 

> https://github.com/UTOFUN/wechat-automation/blob/master/tsconfig.json

Do you know there is a `tsc --init` command?

**Comment by silgal** [comment]
> https://github.com/UTOFUN/wechat-automation/blob/master/.eslintrc.js#L14

Do you know you can remove those eslint rules and use prettier.io instead?

**Comment by silgal** [comment]
| https://github.com/UTOFUN/wechat-automation/blob/master/.gitignore

`npx --yes gitignore node` can generate this file automatically.

**Comment by silgal** [comment]
> https://github.com/UTOFUN/wechat-automation

Do you mean to make this repo public!?

**Comment by vinceyyy** [comment]
> > https://github.com/UTOFUN/wechat-automation
> 
> Do you mean to make this repo public!?

No this will never be public. I write README.md for the sake of me keep forgetting things. Tbh those chat commands probably are not the best choice from the begining.

**Comment by silgal** [comment]
> > > https://github.com/UTOFUN/wechat-automation
> > 
> > 
> > Do you mean to make this repo public!?
> 
> No this will never be public. I write README.md for the sake of me keep forgetting things. Tbh those chat commands probably are not the best choice from the begining.

Oh, fyi, this repo is currently public. @@

**Comment by silgal** [comment]
> https://github.com/UTOFUN/wechat-automation/blob/master/package.json#L12-L13

FYI, direnv.net can help manage env

**Comment by silgal** [comment]
> https://github.com/UTOFUN/wechat-automation/blob/master/package.json#L14

FYI, try jestjs.io and you will forget about mocha.

**Comment by vinceyyy** [comment]
> > > > https://github.com/UTOFUN/wechat-automation
> > > 
> > > 
> > > Do you mean to make this repo public!?
> > 
> > 
> > No this will never be public. I write README.md for the sake of me keep forgetting things. Tbh those chat commands probably are not the best choice from the begining.
> 
> Oh, fyi, this repo is currently public. @@

WHAAAAT. I tried but looks like I cannot make it private. It asks for the org owner to do so. 

I tried to create a new private repo under UTOFUN/ and still cannot do. Is it normal?

**Comment by silgal** [comment]
> > > > > https://github.com/UTOFUN/wechat-automation
> > > > 
> > > > 
> > > > Do you mean to make this repo public!?
> > > 
> > > 
> > > No this will never be public. I write README.md for the sake of me keep forgetting things. Tbh those chat commands probably are not the best choice from the begining.
> > 
> > 
> > Oh, fyi, this repo is currently public. @@
> 
> WHAAAAT. I tried but looks like I cannot make it private. It asks for the org owner to do so.
> 
> I tried to create a new private repo under UTOFUN/ and still cannot do. Is it normal?

We reached private repo limit. Now I remember that's the reason I created UTOFUNdevelop, feel free to move there.

image

**Pull request merged**
